"""Recover conservative road navigation from the preserved MPD 1200 layer.

The original 419D20 allocates width*height*2 primary cells. Even rows
contain tile centers; odd rows contain the four-tile intersections. Only
intersections surrounded by road tiles are opened, keeping forest edges
blocked. This is a local recovery rule, not a recovered official server map.
"""
import argparse,json,struct
from pathlib import Path

def rebuild(source,output,report):
    data=Path(source).read_bytes()
    if data[:4]!=b'MAPD':raise ValueError('Expected original MAPD resource')
    offset=struct.unpack_from('<I',data,0x48)[0]
    kind,_,_,width,height,_,_=struct.unpack_from('<7I',data,offset)
    if (kind,width,height)!=(1200,200,225):raise ValueError('Unexpected original map navigation layer')
    tiles=struct.unpack_from(f'<{width*height}I',data,offset+28)
    bits=[]
    for y in range(height*2):
        row=y//2
        for column in range(width):
            if y>=height*2-1:opened=False
            elif y%2==0:opened=tiles[row*width+column]==1
            else:opened=column+1<width and all(tiles[r*width+c]==1 for r in (row,row+1) for c in (column,column+1))
            bits.append(int(opened))
    runs=bytearray()
    value,count=bits[0],0
    for bit in bits:
        if bit==value and count<255:count+=1
        else:runs.extend((value,count));value,count=bit,1
    runs.extend((value,count))
    while len(runs)%4:runs.extend((0,0))  # consumer stops at its real vector end
    chunks=[runs.hex()[i:i+120] for i in range(0,len(runs.hex()),120)]
    doc='"""Conservative road cells from original 1110101.mpd layer 1200.\n\nGenerated by rebuild_map_navigation.py; original assets are unchanged.\nThe original 419D20 allocates two navigation rows per resource tile row.\nOdd-row intersections are opened only when all four adjacent tiles are road.\n"""\n'
    body=doc+f'NAV_WIDTH={width}\nNAV_SOURCE_HEIGHT={height}\nNAV_HEIGHT={height*2}\nGRID_WIDTH={width*2-1}\nGRID_HEIGHT={height*2-1}\nNAV_RLE=bytes.fromhex(\n'+''.join('    "'+s+'"\n' for s in chunks)+')\n'
    Path(output).write_text(body)
    result={'source':'original map/1110101.mpd','layer_type':kind,'source_width':width,'source_height':height,'source_cells':len(tiles),'native_primary_cells':len(bits),'grid_bounds':[width*2-1,height*2-1],'walkable_cells':sum(bits),'rle_bytes':len(runs),'rule':'Even rows use road tile centers; odd rows require all four surrounding tiles to be road; last unused row remains blocked','limitations':['Conservative local rule reconstructed from asset classifications; official server navigation data unavailable']}
    Path(report).write_text(json.dumps(result,indent=2))
    print(json.dumps(result))

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('source');p.add_argument('output');p.add_argument('--report',required=True);a=p.parse_args()
    rebuild(a.source,a.output,a.report)
