"""Reconstruct land navigation for the original 1120108 resource.

Classes 2 and 3 are used as local land cells; water classes 4 and 6 remain
blocked. This rule is a recovery choice, not the unavailable official server
collision table. Original map resources are never modified.
"""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import struct


def rebuild(source, output, report):
    data = Path(source).read_bytes()
    if data[:4] != b'MAPD':
        raise ValueError('Expected original MAPD')
    layers, extra = struct.unpack_from('<II', data, 0x18)
    candidates = []
    for offset in struct.unpack_from(f'<{layers+extra}I', data, 0x20):
        kind, _, _, width, height, _, _ = struct.unpack_from('<7I', data, offset)
        if kind == 1200:
            candidates.append((offset, width, height))
    if len(candidates) != 1 or candidates[0][1:] != (225, 320):
        raise ValueError('Unexpected original Rashuan navigation layer')
    offset, width, height = candidates[0]
    tiles = struct.unpack_from(f'<{width*height}I', data, offset+28)
    bits = []
    for y in range(height*2):
        row = y//2
        for column in range(width):
            if y >= height*2-1:
                opened = False
            elif y % 2 == 0:
                opened = tiles[row*width+column] in (2, 3)
            else:
                opened = column+1 < width and all(tiles[r*width+c] in (2, 3)
                    for r in (row, row+1) for c in (column, column+1))
            bits.append(int(opened))
    runs = bytearray()
    value, count = bits[0], 0
    for bit in bits:
        if bit == value and count < 255:
            count += 1
        else:
            runs.extend((value, count)); value, count = bit, 1
    runs.extend((value, count))
    while len(runs) % 4:
        runs.extend((0, 0))
    doc = '"""Original 1120108 land navigation; locally reconstructed classes 2/3.\nGenerated by rebuild_rashuan_navigation.py; original server collision unknown.\n"""\n'
    body = doc+f'NAV_WIDTH={width}\nNAV_SOURCE_HEIGHT={height}\nNAV_HEIGHT={height*2}\nGRID_WIDTH={width*2-1}\nGRID_HEIGHT={height*2-1}\nNAV_RLE=bytes.fromhex(\n'
    body += ''.join('    "'+runs.hex()[i:i+120]+'"\n' for i in range(0, len(runs)*2, 120))+')\n'
    Path(output).write_text(body, encoding='utf-8')
    result = {'source': 'original map/1120108.mpd', 'sha256': hashlib.sha256(data).hexdigest(),
              'source_dimensions': [width, height], 'classification_counts': dict(Counter(tiles)),
              'native_primary_cells': len(bits), 'walkable_cells': sum(bits), 'rle_bytes': len(runs),
              'merchant_grid': [141, 313], 'spawn_grid': [139, 313],
              'limitations': ['Original server collision unavailable; land classes 2/3 chosen locally']}
    Path(report).write_text(json.dumps(result, indent=2), encoding='utf-8')
    print(json.dumps(result))


if __name__ == '__main__':
    p = argparse.ArgumentParser(); p.add_argument('source'); p.add_argument('output')
    p.add_argument('--report', required=True); a = p.parse_args()
    rebuild(a.source, a.output, a.report)
